name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: ${{ vars.DOCKERHUB_USERNAME}}/furhaven
  DOCKER_TAG: ${{ github.sha }}
  DOCKERFILE_PATH: ./Dockerfile
  DOCKER_CONTEXT: .
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  REMOTE_PATH: /path/to/deploy/directory

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: furhaven.settings
        DATABASE_URL: sqlite:///db.sqlite3
        SECRET_KEY: test-secret-key
      run: |
        python manage.py test --noinput

  build-and-push:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      run: |
        # Ensure Docker is running
        sudo systemctl start docker || true
        
        # Create buildx builder if it doesn't exist
        if ! docker buildx ls | grep -q builder; then
          docker buildx create --name builder --use
        fi
        
        # Initialize buildx
        docker buildx inspect --bootstrap
        
        # Show buildx info for debugging
        docker buildx ls
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=sha
          type=ref,event=branch
    
    - name: Build and push Docker image
      run: |
        # Set default values if environment variables are not set
        DOCKERFILE_PATH=${DOCKERFILE_PATH:-Dockerfile}
        
        # Build the Docker image
        docker buildx build \
          --file "$DOCKERFILE_PATH" \
          --tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
          --label org.opencontainers.image.revision=${{ github.sha }} \
          --label org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
          --label org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }} \
          --cache-from type=gha \
          --cache-to type=gha,mode=max \
          --progress plain \
          .
        
        # Only push if we're on the main branch
        if [ "${{ github.ref == 'refs/heads/main' }}" = "true" ]; then
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        fi

  deploy:
    name: Deploy to Production
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to server
      env:
        DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}:sha-${{ github.sha }}
      run: |
        # Create necessary directories on remote server
        ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
          "mkdir -p ${{ env.REMOTE_PATH }}/.envs/prod"
        
        # Copy .env file (you might want to manage this differently in production)
        scp -o StrictHostKeyChecking=no .env \
          ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:${{ env.REMOTE_PATH }}/.env
        
        # Pull and run the new container
        ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
          "cd ${{ env.REMOTE_PATH }} && \
           docker-compose pull && \
           docker-compose up -d --force-recreate --no-deps web"
        
        # Run migrations
        ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
          "cd ${{ env.REMOTE_PATH }} && \
           docker-compose exec -T web python manage.py migrate --noinput"
        
        # Collect static files
        ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
          "cd ${{ env.REMOTE_PATH }} && \
           docker-compose exec -T web python manage.py collectstatic --noinput"
        
        # Restart the application
        ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
          "cd ${{ env.REMOTE_PATH }} && \
           docker-compose restart web"
